CREATE TABLE IF NOT EXISTS ENDPOINTHITS (
        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        app varchar(100) NOT NULL,
        uri varchar(100) NOT NULL,
        ip varchar(100) NOT NULL,
        hittimestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS VIEWSTATS (
        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        uri varchar(100) NOT NULL,
        hits BIGINT NOT NULL
);